---
dist: bionic
sudo: required
language: bash
python:
  - "3.7"


branches:
  only:
  - master

matrix:
  fast_finish: true
  include:
  - name: "ansible-2.9"
    env:
      - ANSIBLE_VERSION="2.9.*"
      - MOLECULE_VERSION="2.22"
      - TAG="ansible-2.9"
  - name: "ansible-2.8"
    env:
      - ANSIBLE_VERSION="2.8.*"
      - MOLECULE_VERSION="2.22"
      - TAG="ansible-2.8"
  - name: "ansible-2.7"
    env:
     - ANSIBLE_VERSION="2.7.*"
     - MOLECULE_VERSION="2.22"
     - TAG="ansible-2.7"

services:
  - docker

before_install:
  - |
    docker build -t leandelivery/docker-ansible-ci:$TAG \
    --build-arg ANSIBLE_VERSION \
    --build-arg MOLECULE_VERSION \
    .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
